server: 
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/UserRegisterationSecurityDemo
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


  security:
    user:
      name: admin
      password: admin123
